version: '3'

# Run this file with something like:
# docker-compose --project-name=cen_tos up --remove-orphans
# docker-compose --project-name=cen_tos up --force-recreate --remove-orphans
# Take down with: docker-compose --project-name=cen_tos down
services:
    memcached: # to connect use: docker exec -it centos-memcached bash
        container_name: 'centos-memcached'
        image: 'khalifahks/centos-memcached'
        networks:
            - 'phpworks'
        ports:
            - '11211:11211'

# Apparently there is a lot of custom setup to get Mongo DB to work in a Docker
# container. So try to use the stock image until fixes/work-a-rounds come
# about.
#    mongodb: # to connect use: docker exec -it centos-mongodb bash
#        container_name: 'centos-mongodb'
#        image: 'khalifahks/centos-mongodb'
#        networks:
#            - 'phpworks'
#        ports:
#            - '27017:27017'
# Mapping to host volume will not work on Windows or Mac. See details at:
# https://docs.mongodb.com/manual/administration/production-notes/#fsync-on-directories
#        volumes:
#            - "${mongoDbData}:/var/lib/mongo"
#            - 'C:\OpenSource\docker-mongodb\logs:/var/log/mongodb/'

    nginx: # to connect use: docker exec -it centos-nginx bash
        container_name: 'centos-nginx'
        image: 'khalifahks/centos-nginx'
        networks:
            - 'phpworks'
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - "${NGINX_HOSTS_DIR}:/etc/nginx/conf.d"
            - '${APPS_DIR}:${DOCKER_APPS_DIR}'

    # This is the docker container to login to and build your apps.
    apps: # to connect use: docker exec -it centos-apps bash
        container_name: 'centos-apps'
        image: 'khalifahks/centos-apps'
        depends_on:
            - 'nginx'
        networks:
            phpworks:
                aliases:
                    - 'centos_apps'
        ports:
            - '9000:9000'
        volumes:
            - "${APPS_DIR}:${DOCKER_APPS_DIR}"
networks:
    phpworks: