version: '3'

# Run this file with something like:
# docker-compose --project-name=cen_tos up --force-recreate --remove-orphans
# Take down with: docker-compose --project-name=cen_tos down
services:
    memcached:
        container_name: 'centos-memcached'
        image: 'khalifahks/centos-memcached'
        networks:
            - 'phpworks'
        ports:
            - '11211:11211'

    stock_mongo:
        image: 'mongo'
        networks:
            - 'phpworks'
        ports:
            - '27017:27017'
#        volumes:
#            - "${mongoDbData}:/data/db"

# Apparently there is a lot of custom setup to get Mongo DB to work in a Docker
# container. So try to use the stock image until fixes/work-a-rounds come
# about.
#    mongodb34:
#        container_name: 'centos-mongodb'
#        image: 'khalifahks/centos-mongodb'
#        networks:
#            - 'phpworks'
#        ports:
#            - '27017:27017'
# Mapping to host volume will not work on Windows or Mac. See details at:
# https://docs.mongodb.com/manual/administration/production-notes/#fsync-on-directories
#        volumes:
#            - "${mongoDbData}:/var/lib/mongo"
#            - 'C:\OpenSource\docker-mongodb\logs:/var/log/mongodb/'
    nginx: # to connect use: docker exec -it centos-nginx bash
        container_name: 'centos-nginx'
        image: 'khalifahks/centos-nginx'
        depends_on:
            - 'centos_php'
        networks:
            - 'phpworks'
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - "${nginxConfDir}:/etc/nginx/conf.d"
            - '${appsRoot}:/apps'
            - '${sslCerts}:/ssl-certs'

    php:
        container_name: 'centos-php'
        image: 'khalifahks/centos-php'
        networks:
            phpworks:
                aliases:
                    - 'centos_php'
        ports:
            - '9000:9000'
        volumes:
            # The container directory should match the Nginx share dir so that
            # "root" set in an Nginx configuration server block will work.
            # So "root" in an Ngixn configuration server block should start
            # with this as well.
            - "${appsRoot}:/apps"

    # This is the docker container to login to and build your apps.
    apps:
        container_name: 'centos-apps'
        image: 'khalifahks/centos-apps'
        volumes:
            - "${appsRoot}:/apps"
networks:
    phpworks: