version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: docker:18.06.0-ce-git@sha256:fbcb27ecbc2e7ced9c53010b70d4b62b00d5466d255866b6187881c66ed81e1e
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - run:
          name: Install Docker Compose
          command: |
            wget https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-linux-x86_64
            mv docker-compose-linux-x86_64 docker-compose
            chmod +x docker-compose
            mv docker-compose /usr/local/bin/docker-compose
      - run:
          name: Build application Docker image
          command: |
            ./build-all.sh
      - run:
          name: Run tests
          command: |
            docker-compose up -d
            chmod +x ./verify-expected-images-run.sh
            ./verify-expected-images-run.sh
            docker-compose down
      - deploy:
          name: Push application Docker image
          command: |
            echo $DKR_PASS | docker login -u $DKR_USER --password-stdin
            ./push-all.sh