version: '3.8'

services:
    nodejs_container: # to connect use: docker exec -it alpine-nodejs sh
        container_name: 'alpine-nodejs'
        image: 'khalifahks/alpine-nodejs'
        build:
            dockerfile: 'Dockerfile'
            context: '.'
        entrypoint: 'syslogd'
        command: '-n'
        tty: true
